import React, { createContext, useContext, useState } from 'react';

const LocalizationContext = createContext();

const translations = {
  EN: {
    dashboard: "Dashboard",
    welcome: "Welcome back, Professor",
    search: "Institutional Omni-Search...",
    assets: "Asset Management",
    asset_management: "Asset Management",
    predictive_analytics: "Predictive Analytics",
    resource_hub: "Resource Optimization",
    governance: "Governance Hub",
    governance_hub: "Governance Hub",
    logout: "Secure Sign-Out",
    system_status: "SYSTEM OPERATIONAL",
    academic_hub: "ACADEMIC EXCELLENCE HUB",
    user_control: "User Control",
    risk_analytics: "Risk Analytics",
    system_topology: "System Topology",
    exam_results: "Exam Results",
    certificates: "Certificates",
    student_risk: "Student Risk",
    scholarships: "Scholarships",
    hostel_admin: "Hostel Admin",
    placement_hub: "Placement Hub",
    event_manager: "Event Manager",
    fleet_manager: "Fleet Manager",
    branding_center: "Branding Center",
    strategic_view: "Strategic View",
    executive_command: "Executive Command",
    branding_hub: "Branding Hub",
    financial_growth: "Financial Growth",
    ai_ceo_insights: "AI CEO Insights",
    operational_view: "Operational View",
    resource_telemetry: "Resource Telemetry",
    faculty_analytics: "Faculty Analytics",
    faculty_list: "Faculty List",
    course_matrix: "Course Matrix",
    research: "Research",
    global_hub: "Global Hub",
    career_portal: "Career Portal",
    ward_monitor: "Ward Monitor",
    assignments: "Assignments",
    syllabus_monitor: "Syllabus Monitor",
    research_bureau: "Research Bureau",
    attendance: "Attendance",
    mark_attendance: "Mark Attendance",
    leave_requests: "Leave Requests",
    quiz_engine: "Quiz Engine",
    academic: "ACADEMIC",
    syllabus: "Syllabus",
    time_table: "Time Table",
    academic_score: "Academic Score",
    quizzes: "Quizzes",
    support: "Support",
    events_clubs: "Events & Clubs",
    digital_id: "Digital ID",
    transit: "Transit",
    services: "SERVICES",
    fees_dues: "Fees & Dues",
    library: "Library",
    hostel_life: "Hostel Life",
    placement_cell: "Placement Cell",
    bus_schedule: "Bus Schedule",
    personal: "PERSONAL",
    profile: "Profile",
    security: "Security",
    ai_assistant: "AI Assistant",
    core: "CORE",
    node_primary: "Node Primary",
    analytics_hub: "Analytics Hub",
    notice_board: "Notice Board",
    grievance: "Grievance",
    campus_metaverse: "Campus Metaverse",
    master_schedule: "Master Schedule",
    system_config: "System Config",
    omni_search: "Omni Search"
  },
  OR: { // Odia
    dashboard: "ଡ୍ୟାସବୋର୍ଡ",
    welcome: "ସ୍ଵାଗତ ଶୁଭେଚ୍ଛା, ପ୍ରଫେସର",
    search: "ପ୍ରତିଷ୍ଠାନ ସନ୍ଧାନ...",
    assets: "ସମ୍ପତ୍ତି ପରିଚାଳନା",
    asset_management: "ସମ୍ପତ୍ତି ପରିଚାଳନା",
    predictive_analytics: "ଭବିଷ୍ୟବାଣୀ ବିଶ୍ଳେଷଣ",
    resource_hub: "ସମ୍ବଳ ଅପ୍ଟିମାଇଜେସନ୍",
    governance: "ଶାସନ ହବ୍",
    governance_hub: "ଶାସନ ହବ୍",
    logout: "ପ୍ରସ୍ଥାନ",
    system_status: "ସିଷ୍ଟମ୍ ଚାଲୁଛି",
    academic_hub: "ଏକାଡେମିକ୍ ହବ୍",
    user_control: "ଉପଭୋକ୍ତା ନିୟନ୍ତ୍ରଣ",
    risk_analytics: "ବିପଦ ବିଶ୍ଳେଷଣ",
    system_topology: "ସିଷ୍ଟମ୍ ଟପୋଲୋଜି",
    exam_results: "ପରୀକ୍ଷା ଫଳାଫଳ",
    certificates: "ପ୍ରମାଣପତ୍ର",
    student_risk: "ଛାତ୍ର ବିପଦ",
    scholarships: "ବୃତ୍ତି",
    hostel_admin: "ହଷ୍ଟେଲ ପ୍ରଶାସନ",
    placement_hub: "ପ୍ଲେସମେଣ୍ଟ ହବ୍",
    event_manager: "ଇଭେଣ୍ଟ ମ୍ୟାନେଜର",
    fleet_manager: "ଫ୍ଲାଇଟ୍ ମ୍ୟାନେଜର",
    branding_center: "ବ୍ରାଣ୍ଡିଂ କେନ୍ଦ୍ର",
    strategic_view: "ରଣନୀତିକ ଦୃଶ୍ୟ",
    executive_command: "କାର୍ଯ୍ୟନିର୍ବାହୀ କମାଣ୍ଡ",
    branding_hub: "ବ୍ରାଣ୍ଡିଂ ହବ୍",
    financial_growth: "ଆର୍ଥିକ ଅଭିବୃଦ୍ଧି",
    ai_ceo_insights: "AI CEO ଅନ୍ତର୍ଦୃଷ୍ଟି",
    operational_view: "କାର୍ଯ୍ୟକ୍ଷମ ଦୃଶ୍ୟ",
    resource_telemetry: "ଉତ୍ସ ଟେଲିମେଟ୍ରି",
    faculty_analytics: "ଅଧ୍ୟାପକ ବିଶ୍ଳେଷଣ",
    faculty_list: "ଅଧ୍ୟାପକ ତାଲିକା",
    course_matrix: "ପାଠ୍ୟକ୍ରମ ମାଟ୍ରିକ୍ସ",
    research: "ଗବେଷଣା",
    global_hub: "ଗ୍ଲୋବାଲ୍ ହବ୍",
    career_portal: "କ୍ୟାରିଅର୍ ପୋର୍ଟାଲ୍",
    ward_monitor: "ୱାର୍ଡ ମନିଟର୍",
    assignments: "ଆସାଇନମେଣ୍ଟ",
    syllabus_monitor: "ପାଠ୍ୟକ୍ରମ ମନିଟର୍",
    research_bureau: "ଗବେଷଣା ବ୍ୟୁରୋ",
    attendance: "ଉପସ୍ଥାପନ",
    mark_attendance: "ଉପସ୍ଥାପତି ଚିହ୍ନଟ",
    leave_requests: "ଛୁଟି ଅନୁରୋଧ",
    quiz_engine: "କ୍ୱିଜ୍ ଇଞ୍ଜିନ୍",
    academic: "ଏକାଡେମିକ୍",
    syllabus: "ପାଠ୍ୟକ୍ରମ",
    time_table: "ସମୟ ସାରଣୀ",
    academic_score: "ଏକାଡେମିକ୍ ସ୍କୋର",
    quizzes: "କ୍ୱିଜ୍",
    support: "ସହାୟତା",
    events_clubs: "ଇଭେଣ୍ଟ ଏବଂ କ୍ଲବ",
    digital_id: "ଡିଜିଟାଲ୍ ID",
    transit: "ଟ୍ରାଞ୍ଜିଟ୍",
    services: "ସେବା",
    fees_dues: "ଫି ଏବଂ ବକେୟା",
    library: "ଗ୍ରନ୍ଥାଗାର",
    hostel_life: "ହଷ୍ଟେଲ ଜୀବନ",
    placement_cell: "ପ୍ଲେସମେଣ୍ଟ ସେଲ",
    bus_schedule: "ବସ୍ ସମୟସୂଚୀ",
    personal: "ବ୍ୟକ୍ତିଗତ",
    profile: "ପ୍ରୋଫାଇଲ୍",
    security: "ସୁରକ୍ଷା",
    ai_assistant: "AI ସହାୟକ",
    core: "କୋର",
    node_primary: "ପ୍ରାଥମିକ ନୋଡ୍",
    analytics_hub: "ବିଶ୍ଳେଷଣ ହବ୍",
    notice_board: "ସୂଚନା ଫଳକ",
    grievance: "ଅଭିଯୋଗ",
    campus_metaverse: "କ୍ୟାମ୍ପସ ମେଟାଭର୍ସ",
    master_schedule: "ମାଷ୍ଟର ସିଡ୍ୟୁଲ୍",
    system_config: "ସିଷ୍ଟମ୍ କନଫିଗ୍",
    omni_search: "ଓମନି ସନ୍ଧାନ"
  },
  HI: { // Hindi
    dashboard: "डैशबोर्ड",
    welcome: "स्वागत है, प्रोफेसर",
    search: "संस्थागत खोज...",
    assets: "संपत्ति प्रबंधन",
    asset_management: "संपत्ति प्रबंधन",
    predictive_analytics: "पूर्वानुमानात्मक विश्लेषण",
    resource_hub: "संसाधन अनुकूलन",
    governance: "शासन केंद्र",
    governance_hub: "शासन केंद्र",
    logout: "लॉगआउट",
    system_status: "प्रणाली चालू है",
    academic_hub: "अकादमिक केंद्र",
    user_control: "उपयोगकर्ता नियंत्रण",
    risk_analytics: "जोखिम विश्लेषण",
    system_topology: "प्रणाली टोपोलॉजी",
    exam_results: "परीक्षा परिणाम",
    certificates: "प्रमाण पत्र",
    student_risk: "छात्र जोखिम",
    scholarships: "छात्रवृत्ति",
    hostel_admin: "छात्रावास प्रशासन",
    placement_hub: "प्लेसमेंट हब",
    event_manager: "ईवेंट मैनेजर",
    fleet_manager: "बेड़ा प्रबंधक",
    branding_center: "ब्रांडिंग केंद्र",
    strategic_view: "रणनीतिक दृश्य",
    executive_command: "कार्यकारी कमान",
    branding_hub: "ब्रांडिंग हब",
    financial_growth: "वित्तीय विकास",
    ai_ceo_insights: "AI CEO अंतर्दृष्टि",
    operational_view: "परिचालन दृश्य",
    resource_telemetry: "संसाधन टेलीमेट्री",
    faculty_analytics: "संकाय विश्लेषण",
    faculty_list: "संकाय सूची",
    course_matrix: "पाठ्यक्रम मैट्रिक्स",
    research: "अनुसंधान",
    global_hub: "वैश्विक हब",
    career_portal: "करियर पोर्टल",
    ward_monitor: "वार्ड मॉनिटर",
    assignments: "असाइनमेंट",
    syllabus_monitor: "पाठ्यक्रम मॉनिटर",
    research_bureau: "अनुसंधान ब्यूरो",
    attendance: "उपस्थिति",
    mark_attendance: "उपस्थिति दर्ज करें",
    leave_requests: "छुट्टी के अनुरोध",
    quiz_engine: "प्रश्नोत्तरी इंजन",
    academic: "अकादमिक",
    syllabus: "पाठ्यक्रम",
    time_table: "समय सारणी",
    academic_score: "अकादमिक स्कोर",
    quizzes: "प्रश्नोत्तरी",
    support: "सहायता",
    events_clubs: "ईवेंट और क्लब",
    digital_id: "डिजिटल आईडी",
    transit: "पारगमन",
    services: "सेवाएं",
    fees_dues: "शुल्क और बकाया",
    library: "पुस्तकालय",
    hostel_life: "छात्रावास जीवन",
    placement_cell: "प्लेसमेंट सेल",
    bus_schedule: "बस समय सारणी",
    personal: "व्यक्तिगत",
    profile: "प्रोफ़ाइल",
    security: "सुरक्षा",
    ai_assistant: "AI सहायक",
    core: "कोर",
    node_primary: "प्राथमिक नोड",
    analytics_hub: "विश्लेषण हब",
    notice_board: "सूचना पट्ट",
    grievance: "शिकायत",
    campus_metaverse: "कैंपस मेटावर्स",
    master_schedule: "मास्टर शेड्यूल",
    system_config: "सिस्टम कॉन्फ़िगरेशन",
    omni_search: "ओमनी खोज"
  }
};

export const LocalizationProvider = ({ children }) => {
  const [lang, setLang] = useState('EN');

  const t = (key) => {
    return translations[lang][key] || translations['EN'][key] || key;
  };

  return (
    <LocalizationContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LocalizationContext.Provider>
  );
};

export const useLocalization = () => useContext(LocalizationContext);
